### ISSUE TITLE
Cannot move cursor left/right in Search field

### ISSUE THREAD

**Issue by melvinwevers** [UUDigitalHumanitieslab/texcavator#119]
When inputting a query in the search field (which is rather short), it is not possible to scroll left or right through your input using your arrow keys.

I tested this in Safari. In Google Chrome searching works.

**Comment by melvinwevers** [comment]
Also, searching logs me out of the program, prompting the login screen.

**Comment by jgonggrijp** [comment]
I took the page refresh issue to a separate ticket and fixed it. Please report each issue in a separate ticket next time.

I'm still looking into the arrow key issue.

**Comment by jgonggrijp** [comment]
Technical note: the issue is caused by the fact that the form node receives focus when the search input is active. When an arrow key is pressed, focus is shifted to the other elements of the toolbar, thus preventing further editing of the search input. I don't know how to prevent this behaviour, yet.

**Comment by mhkuu** [comment]
This might be a solution: https://bugs.dojotoolkit.org/ticket/16266, see comment by `musicdemo`. If we go this way we should implement this for the date selectors as well.

**Comment by jgonggrijp** [comment]
Yes, that looks like it should work. I'm going to try that later. Thanks for the tip.

FWIW, I'm amazed that the Dojo developers insist on going against all conventions by using the arrow keys for something that the tab key is normally used for.
