### ISSUE TITLE
TF-IDF based word clouds

### ISSUE THREAD

**Issue by PimHuijnen** [UUDigitalHumanitieslab/texcavator#69]
In addition to our word clouds based on absolute frequency, I would like to use TF-IDF based word clouds. We use word clouds as a form of visualisation to give insight in the 'context' of a certain domain (query). As it is now, the underlying assumption is that raw frequencies of word use are most telling for this context. In my opinion, a TF-IDF score would result in an equally good - if not better - way to give an idea of the particular context of a query.

To implement this, we could use a word list based on all Dutch national, 20th century newspapers and determine the TF-IDF score of individual queries against this standard dictionary. Ideally, the user should have the option to build word clouds based on frequency or on TF-IDF.

**Comment by jgonggrijp** [comment]
If I understand your request correctly, you want global IDF scores to be calculated once, then be offered the possibility to divide term frequencies in the word cloud of a particular query by the corresponding global IDF scores. Is that correct?

**Comment by PimHuijnen** [comment]
Spot on!

**Comment by mhkuu** [comment]
This is available now on texcavator.hum.uu.nl; it's a setting in the 'Cloud' tab. Check it out and let me know what you think :-)

The inverse document frequencies are currently based on a small part of the corpus; I'll give some details next week on this.

**Comment by mhkuu** [comment]
Decided to create two word lists: one for 1900-1945 and one for 1945-1990. 

We will look at the possibility to use a [trie](https://en.wikipedia.org/wiki/Trie) to make lookup faster.

**Comment by PimHuijnen** [comment]
I wanted to propose the exact same thing as José, so I fully agree with her suggestion to consider the WWII period on its own. It forms such an anomaly in this corpus that it would have a distorting effect on the idf scores. Just to be precise, I would propose to calculate idf scores for the periods 01-01-1900 - 31-12-1939, for 01-01-1940 - 31-12-1945, and for 01-01-1946 - 31-12-1989.

**Comment by JosedeKruif** [comment]
Glad we agree! However, I would like to propose to take the “real” data for the periods. That would give us a set before WW II = until 15-05-1940 and  WW II 16-05-1940  until 08-05-1945. (one or two days after capitulation and ditto after formal end of war).

**Comment by jesperverhoef** [comment]
Just to be sure (have to mention this in my dissertation): is the IDF-score currently based on the periods José suggested?

**Comment by mhkuu** [comment]
Hi @jesperverhoef, good you're asking, the time frames are indeed as José proposed:

* pre: from 1 Jan 1900 up to and including 15 May 1940
* war: from 16 May 1940 up to and including 8 May 1945
* post: from 9 May 1945 up to and including 31 Dec 1990 

Note the last date is 31 Dec 1990 (instead of 1989) as this is also the default end search date.

This will also be included in the user documentation (almost finished!).

**Comment by jesperverhoef** [comment]
Thanks! Another question, which I will pose in Dutch, for I'm afraid otherwise I will not be able to express what I'm struggling with:

Wat berekent Texcavator precies wanneer een woordenwolk genormaliseerd ('normalized') wordt? In 'configurations' staat: 'Normalize using inverse document frequency'. Betekent dit dat TF/IDF toegepast wordt? Zo ja, wat is dan de TF- en wat de IDF-waarde?

Laat me je meenemen in mijn gedachtegang; dit helpt misschien duidelijk te maken waar / als ik zaken niet begrijp of de plank missla. Als ik het wel heb bestaat TF/IDF normaliter uit drie componenten:
 
-het totale aantal artikelen
-het totale aantal artikelen waarin een bepaald woord voorkomt (waarbij idf het eerste gedeeld door het tweede is) 
- het totale aantal keren dat dat woord in het corpus voorkomt (= tf).
 
Aannemende dat Texcavator inderdaad een lijst met TF/IDF-scores genereert, dan is mijn vraag: voor welk(e) van deze componenten gebruikt Tex het subcorpus en voor welk(e)het referentiecorpus?

Een concreet voorbeeld: in mijn geval ben ik geïnteresseerd in alle krantenartikelen waarin de zoekopdracht (rolprent film bios*oop movie cinema kinema) in de periode van 1-1-1920 t/m 30-12-1924 resulteerde, namelijk 30.272 krantenartikelen. Dit is mijn subcorpus. Daarbinnen ben ik o.m. geïnteresseerd in het woord 'amerika'. 

Is het zo dat Texcavator het totale aantal artikelen in het subcorpus (30.272) deelt door het aantal artikelen in het subcorpus waarin ‘amerika’ voorkomt? Als dit zo is, wordt de score die daaruit voortvloeit vervolgens afgezet tegen het aantal keren dat het woord ‘amerika’ voorkomt in het referentiecorpus (i.c. het pre-oorlogse corpus, zoals hierboven omschreven)?  En dus niet tegen het aantal keren dat het woord voorkomt in het subcorpus van 30.272 (zoals in de KB Keyword generator, ontwikkeld door Pim en een KB-programmeur)?

**Comment by mhkuu** [comment]
Hoi Jesper,

In de genormaliseerde wordcloud wordt de frequentie van een woord in de documenten van je zoekopdracht (=**tf**, wat je normaal ook al ziet in de niet-genormaliseerde word clouds) vermenigvuldigt met de **idf**-score van de term in het referentiecorpus (dus dat is inderdaad anders dan de keyword generator). De idf-score voor een term is _log(aantal documenten in referentiecorpus/aantal documenten waarin de term voorkomt)_. Het idee hierbij is dat met deze normalisatie in de word clouds gecorrigeerd wordt voor hoogfrequente woorden (in het algemeen, niet specifiek voor je zoekopdracht). 

Ik hoop dat dit duidelijk is!

**Comment by jesperverhoef** [comment]
Heel duidelijk, dank! Andere vraag: bestaan de data waarop de IDF-score  in Texcavator berust op álle beschikbare krantenkopij in de drie genoemde periodes, dus artikelen, advertenties, illustraties en familieberichten tezamen? Of louter op de artikelen? (Ik vermoed het eerste, maar 't leek me raadzaam dit toch even te verifiëren.)

**Comment by mhkuu** [comment]
Niet helemaal alle kopij; het gaat alleen om kopij uit de distributie "landelijk", maar inderdaad wel van alle artikelsoorten.
