### ISSUE TITLE
Timelines normalization based on filter settings

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/texcavator#87]
From @melvinwevers in #71: 

> Which makes me wonder. Should we divide the frequency by the total number of documents in the newspaper archive, or by the total number of articles within the specific corpus we are investigation (based on our meta-data this could be Dutch/National/Article. 

From @melvinwevers in #86: 

> If I recall correctly we discussed different ways of normalizing the timeline. 
I think we discussed that it now takes the peak and normalizing everything according to this peak. 
Another option would be to normalize by dividing every year with the number of documents in this year. If we would do this we would run into the problem of what the total number of documents would be—everything, only the national newspapers. In other words, should this be dependent on your meta-data filtering.

The idea is that instead of normalizing on the whole corpus, we normalize based on the filter settings. 

Note to self: we might want to collect the numbers of documents offline (like it happens now), even though that will complicate our database structure.

**Comment by melvinwevers** [comment]
After giving it some thought (my days in social science are far in the past), I think we need to be able to normalize based on
* entire corpus of documents in national/regional newspapers 
* entire corpus of articles in national/regional newspapers
* entire corpus of advertisements in national/regional newspapers.

I think we don't need to further specify this according to possible configurations of meta-data.

**Comment by JosedeKruif** [comment]
??? Timeline gives the frequency of a word. Then you want to divide that by the number of pages (documents), the number of articles, all the advertisements? What's wrong with good old tf/idf? Moreover: advertisements are very badly ocr'd. The noisy layout results in several adds being presented as one advertisement. This would make the outcome of such a division very unreliable indeed.

**Comment by melvinwevers** [comment]
Indeed, three different ways of normalizing, based on the corpus you are investigation. 

There is nothing wrong with tf/idf. But because of the ocr problems, it think it's better to look at the number of documents in the corpus. Because of the worse OCR quality in advertisements, it also helps to be able to normalize based on articles/ad/everything. 

You are right that sometimes multiple ads are indexed as one, but despite this problem, (which I do address in my chapters) I think a normalization of the timeline would offer additional information, in addition to absolute numbers that are now given. 

The normalization that Texcavator offers now only tells us something about the distribution within the query itself, and does not help to compensate (in part) for the changes in the corpus.

**Comment by melvinwevers** [comment]
Maar laten we dit donderdag verder bespreken.

**Comment by mhkuu** [comment]
At the user meeting we decided upon implementing relative frequencies (which take the filter settings into account). This was implemented in 115e6397c05c2033fed82b4421a665266f0cb9f8.
