### ISSUE TITLE
Matching quoted phrases exactly

### ISSUE THREAD

**Issue by jgonggrijp** [UUDigitalHumanitieslab/texcavator#88]
@melvinwevers wrote in #78:
> I just tried this query: "land van de gangster". If I'm correct, this should look for this particular string, however, it finds an article with the following sentence: "Zeer trots op deze dienst aan het hoogste uitvoerende gezag van zün land heeft de gangster zijn „dienst" overal rondgebazuind"

> Could this be because stop-words are filtered out during indexation/tokenization?

> This makes it very difficult to determine how often a particular phrase occurred in the corpus.

The ES manual states that a quoted phrase will search for all words in the phrase in the given order. If stop words are filtered out, either during indexation or during the search, that may indeed explain why the quoted sentence matches your query.

I don't know off the top of my head whether stop words are filtered out during indexation. If they are, I suspect not doing so is not an option (if it solves the problem at all). It would certainly inflate the index and possibly slow down queries.

Another option would be that you download your search results, then use another tool to search for exact occurrences of your search phrase within those results. This is a job that `grep` can do very well. It has a flag (`-c`) that causes it to count the number of occurrences for you. Other tools (SPSS et al?) probably can do this job, too. Would this solve your issue?

**Comment by melvinwevers** [comment]
It is definitely an option to export this query and count the exact phrasing. However, it would be preferable for quick exploration of the corpus to do this within Texcavator. Users now expect to be able to use parentheses to query for exact phrases. Another option is Delpher. Here, I can search for exact phrase, however, their index is different than Texcavator's, and I would like to do my analyses on the same corpus.

**Comment by mhkuu** [comment]
I don't see this happening on our development environment (http://texcavator.hum.uu.nl/). On there I get one result for "land van de gangster", just like in Delpher. 

Further analysis indicates that the analyzer settings on the live version are off from the development version; stopwords are indeed filtered during indexing, while on the development version this is not the case: 

Live index (used on texcavator.surfsaralabs.nl):
```
{
  "kb_20141015" : {
    "settings" : {
      "index" : {
        "uuid" : "cxAnvIyzQp6rspBtTG9UYQ",
        "analysis" : {
          "analyzer" : {
            "default" : {
              "type" : "standard",
              "stopwords" : "_dutch_"
            }
          }
        },
        "number_of_replicas" : "2",
        "number_of_shards" : "16",
        "version" : {
          "created" : "1020499"
        }
      }
    }
  }
}
```

Development index (used on texcavator.hum.uu.nl):

```
{
  "kb_20150921" : {
    "settings" : {
      "index" : {
        "creation_date" : "1442918211243",
        "uuid" : "pV74FpLySUCOG4UvutFRfw",
        "number_of_replicas" : "1",
        "analysis" : {
          "filter" : {
            "dutch_stemmer" : {
              "type" : "stemmer",
              "name" : "dutch_kp"
            }
          },
          "analyzer" : {
            "dutch_analyzer" : {
              "type" : "custom",
              "filter" : [ "standard", "lowercase", "dutch_stemmer" ],
              "tokenizer" : "standard"
            }
          }
        },
        "number_of_shards" : "18",
        "refresh_interval" : "600s",
        "version" : {
          "created" : "1070199"
        }
      }
    }
  }
}
```

Pretty soon we'll be switching to the development index, so I suggest we use that as it's closer to Delpher. However, we can never guarantee that Delpher and Texcavator produce the same results, Delpher might use an alternative scheme/software for indexing/tokenizing/analyzing. Preferably Texcavator produces better results than Delpher :-) 

Note: From the index names you do see that this behaviour was in place since at least October 2014. 

Note to self: results produced with `curl 145.100.29.229:9200/kb/_settings/?pretty` on the live index.

**Comment by jgonggrijp** [comment]
If I'm right, we can close this after moving to the new production server.

**Comment by mhkuu** [comment]
You're correct, and since we've done this yesterday, this is now a non-issue!
